### ISSUE TITLE
请问你的TV Spider怎么使用啊？能否出一个视频教程。谢谢

### ISSUE THREAD

**Issue by BruceLeeX** [jadehh/jadehh#1]
请问你的TV Spider怎么使用啊？能否出一个视频教程。谢谢

你比如我如何使用到猫影视1.1.3_preview4中去

**Comment by jadehh** [comment]
看下面这个分支
https://github.com/jadehh/TVSpider/tree/dist

**Comment by jadehh** [comment]
Clone到自己的私仓中,配置自己的源地址，一定要是私仓，CatVodOpen不支持公共仓库
