### ISSUE TITLE
蜂蜜影视更改界面语言

### ISSUE THREAD

**Issue by howard868** [jadehh/jadehh#2]
大佬，需要你帮个忙。蜂蜜影视挺好用，就是默认的英文界面非常拉垮，我找不到语言设置的选项。好像是不能手动设置语言，而是自动跟系统走，但是我的fire tv系统没有中文。有没有什么办法手动更改蜂蜜界面语言？也看不到蜂蜜github有提issue的选项。

**Comment by jadehh** [comment]
附上你的版本截图，晚点我给你改个版本。

**Comment by howard868** [comment]
> 附上你的版本截图，晚点我给你改个版本。

![image](https://github.com/jadehh/jadehh/assets/122852334/f1f39111-a322-4095-b2f2-2b1523df1c5e)

![image](https://github.com/jadehh/jadehh/assets/122852334/66a1a9a6-56f5-487c-b0fe-a1484cc0e7a2)

**Comment by jadehh** [comment]
![image](https://github.com/jadehh/jadehh/assets/20532462/8994fdd5-11d2-4edf-aeb2-323c27e2f1d0)
[代码查看此次提交](https://github.com/jadehh/FongMiTV/commit/64e6ad575eb300f33a18df47b13db8d20bb87030)
有问题转[ISSUE](https://github.com/jadehh/FongMiTV/issues)
