### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by sds612401** [jadehh/jadehh#3]
安卓/ios如何去配置接口文件。求一个详细的教程，谢谢。

**Comment by jadehh** [comment]
[Wikis](https://github.com/jadehh/TVSpider/wiki)
用的是猫影视吗
![image](https://github.com/jadehh/jadehh/assets/20532462/d219c91e-071a-4b5e-869e-01fa22096e3b)

**Comment by sds612401** [comment]
对，用的是猫影视1.1.4，但是我不会配置接口，求教，感谢大佬

**Comment by jadehh** [comment]
https://omii.top/1296.html
https://omii.top/2019.html
看下这两个文档，然后将TVSpier中的dist分支导入到自己的Gitee私仓中就可以了。

**Comment by sds612401** [comment]
上传文件我不知道上传哪一些文件，还有lib里面的文件，有的文件在你的库里找不到。求开导，谢谢

**Comment by jadehh** [comment]
https://github.com/jadehh/TVSpider/tree/dist 该分支下载的所有文件上传到你自己的私仓库中，这个分支对应的就是新版本猫影视的配置文件

**Comment by sds612401** [comment]
是上传到lib这个文件里吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月16日(星期四) 下午2:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jadehh/jadehh] 配置问题 (Issue #3)














 
https://github.com/jadehh/TVSpider/tree/dist 该分支下载的所有文件上传到你自己的私仓库中，这个分支对应的就是新版本猫影视的配置文件

**Comment by jadehh** [comment]
## 仓库导入
导入Github仓库
![4376c899c5c35fdd132b5dc777ac191](https://github.com/jadehh/jadehh/assets/20532462/c72b1121-a750-4938-9c64-5430e75eee87)
设置私有
![96036eb58cb8bff07c584f16cfd49fb](https://github.com/jadehh/jadehh/assets/20532462/68791923-ab3d-45a5-830f-669fbf450788)


## Token获取
![4ecd40aa848910ff229166d7fe2327d](https://github.com/jadehh/jadehh/assets/20532462/3436b308-5724-4647-bc96-88d0cf0748c0)


## 导入地址
![image](https://github.com/jadehh/jadehh/assets/20532462/3980d4dc-a988-4f23-a111-1ba158651fa1)

地址格式为
```bash
gitee://Token@gitee.com/Gitee账户名称/Gitee仓库名称/Gitee分支名称/index.js.md5
```
> 分支名称固定为dist

下面这个是我用的
```bash
gitee://Token@gitee.com/jadehh_743/TVSpider/dist/index.js.md5
```
